// This file is auto-generated by `wrangler types`. The stub below is here so
// `npm run type-check` passes before you run `wrangler types` for the first time.
// After your first `npx wrangler types`, this file will be overwritten with the
// full Cloudflare types and bindings.

interface Env {
	SERVICENOW_INSTANCE_URL: string;
	SERVICENOW_USERNAME: string;
	SERVICENOW_PASSWORD: string;
	ENABLE_SCRIPT_EXECUTION?: string;
	MCP_OBJECT: DurableObjectNamespace;
}
